name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spirl
          environment-file: ./environment.yml
          auto-update-conda: true
          auto-activate-base: false
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: Check conda env
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Build SPIRL JupyterBook
        run: jupyter-book build spirl
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./spirl/_build/html
          publish_branch: gh-pages