name: 'Trigger-Binder-build'
on:
  workflow_run:
    workflows: ["github pages"]
    types:
      - completed

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: cjtu/spirl
          service-name: gh